### ISSUE TITLE
Ability to change the keys?

### ISSUE THREAD

**Issue by WeatherGod** [matplotlib/cycler#11]
While I totally agree that we should not be able to change the values associated with each key, what about being able to change out the key names? A use case would be for normalizing property names:
```
>>> c = cycler('color', 'rgb') + cycler('lw', [1, 2, 3])
>>> c.key_change('lw', 'linewidth')
cycler('color', ['r', 'g', 'b']) + cycler('linewidth', [1, 2, 3])
```

**Comment by tacaswell** [comment]
You can do

```python
c2 = cycler('new_name', c1)
```
which accomplishes the same thing for a single cycler.

I am hesitant, but see the use case for normalization which makes me 75/25 in favor.

**Comment by WeatherGod** [comment]
The problem with that approach is that it only works for a single-property cycler. If the cycler is a multi-property one...
```
>>> from cycler import cycler
>>> c = cycler('color', 'rgb') + cycler('lw', [1, 2, 3])
>>> c2 = cycler('linewidth', c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/cycler.py", line 301, in cycler
ValueError: Can not create Cycler from a multi-property Cycler
```

**Comment by WeatherGod** [comment]
Would it help if I implement it for you? (it is a slow day today in the office)

**Comment by tacaswell** [comment]
Yes
