### ISSUE TITLE
Cycler doesn't cycle

### ISSUE THREAD

**Issue by OceanWolf** [matplotlib/cycler#2]
This issue falls mainly along the lines of semantics.  I would expect something called ``Cycler`` to do the cycling itself, instead it just represents a list, of course we want to create a cycle object from the list, but nothing in "``Cycler``" actually promotes this...

Perhaps naming this ``CycleHelper`` would help, and ooh, just had an idea to combine this with my own cycling experiments... one moment while I make a PR... :smiling_imp:.

**Comment by OceanWolf** [comment]
Never mind on that PR, silly idea wanting to create a ``class ChainedCycle(cycle)``, wrapper around the ``CycleHelper`` but I don't think it would get that much use as the ``CycleHelper`` remains recyclable via ``cycle(CycleHelper)``, but a ``ChainedCycle`` would becomes a one-shot device...

**Comment by tacaswell** [comment]
The first version of this did return it's iter wrapped in `intertools.cycle`, but it ended up being very awkward to work with as most of the time you really want the finite version of the cycle.

Using `itertools.cycle` is in the first example http://matplotlib.org/cycler/#examples 

I was hoping the name would encourage the use of these objects with `itertools.cycle`

**Comment by OceanWolf** [comment]
Sure, but a finite version by definition doesn't cycle.

How about a cycling flag? if currently cycling and you switch the flag off it will stop at the end of the next cycle, we could forego ``itertools.cycle`` and just use yield...
