### ISSUE TITLE
Include tests in release

### ISSUE THREAD

**Issue by FRidh** [matplotlib/cycler#31]
Please include tests in the archives of releases. This makes it easier for packagers to test whether their packaged version works. Thanks!

**Comment by tacaswell** [comment]
Duplicate of #21 which we thought we fixed :disappointed: 

Looks like the manifest include the test _running_ script, but not the actual tests.

**Comment by tacaswell** [comment]
If you grab the tarball from github instead of pip you will get the expected files.
