### ISSUE TITLE
DOC: Minor typo in `Mutiplication` section

### ISSUE THREAD

**Issue by afvincent** [matplotlib/cycler#35]
I didn't find any function called `prod()` in `itertools`, so I assume that `itertools.prod()` in the documentation (section "Multiplication") refers in reality to `itertools.product()`. 

Besides is "outer product" the correct name for this product? In `itertools.product()` docstring, the name "Cartesian product" is used and Wikipedia doesn't seem to give the exact same definition for the two products (see [Cartesian](https://en.wikipedia.org/wiki/Cartesian_product) vs [outer](https://en.wikipedia.org/wiki/Outer_product)).

**Comment by tacaswell** [comment]
Yes, that should be `itertools.product`, can you put in a PR with that change?

Cartesian product is a bit more accurate (in that the result is the same dimensional), but not perfect in that the result is ordered  (ex `a[::-1]*b != a *b`) where as sets are not.  

It is more of a raveled version of of the outer product.

**Comment by afvincent** [comment]
PR submitted.

I see your point on "outer product" rather than "Cartesian product", eventhough `itertools.product` is describded as "Cartesian product" in its own docstring, which forgets the fact it returns an ordered result (as it is also very common on the web to see questions and topics about the "Cartesian product of lists").

**Comment by WeatherGod** [comment]
closed via #36

**Comment by WeatherGod** [comment]
thanks for fixing the documentation!

**Comment by afvincent** [comment]
You're welcome.
