### ISSUE TITLE
Ability to update 1 or more parts of a cycler?

### ISSUE THREAD

**Issue by WeatherGod** [matplotlib/cycler#6]
Don't know how feasible this would be, but I am thinking of a case where there is an existing cycler object (possibly a default cycler), and the user needs to swap out a component of the composed cycler, such as changing the color cycle.

One possible stumbling block might be if the object is in the middle of being cycled?

**Comment by tacaswell** [comment]
I am :-1: on this, I think exposing the internals to mutation in a consistent way will not be easy.

This might even be a good reason to rip out the in-place operations.

**Comment by efiring** [comment]
Agreed.  Simpler is better for this.  Assembling a new instance out of parts of old ones seems likely to be simpler and more robust than any internal mutation.  This type of operation is unlikely to be performed often, so even if it takes slightly longer, the cost is negligible.

**Comment by tacaswell** [comment]
Closing as 'won't fix'
