### ISSUE TITLE
https://matplotlib.org/cycler/ is outdated

### ISSUE THREAD

**Issue by anntzer** [matplotlib/cycler#76]
It still points to 0.10.0.

**Comment by QuLogic** [comment]
I guess I just need to build and push to the `gh-pages` branch, but when I build, the side bar only has `cycler`, `Cycler`, and `concat`, instead of the ToC side bar like it does in the existing page.

**Comment by timhoffm** [comment]
Without having a closer look, I suspect this is a change on the sphinx side. The existing page was built with 1.3.5.

**Comment by QuLogic** [comment]
The basic theme is after the images. However, I found on that page the sidebar settings, and I think I have it working the same again.

**Comment by QuLogic** [comment]
Should be good now.
