### ISSUE TITLE
Python 3.10 compatibility

### ISSUE THREAD

**Issue by yp25** [matplotlib/cycler#83]
On Python 3.10.8 setup.py  incorrectly raises 
ERROR: Ignored the following versions that require a different python version: 0.7 Requires-Python >=3.6, <3.7; 0.8 Requires-Python >=3.6, <3.7
ERROR: Could not find a version that satisfies the requirement dataclasses==0.7 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for dataclasses==0.7

instead of 
`python_requires='>=3.6',`

please consider to change with compare version as number rather than strings

**Comment by QuLogic** [comment]
I don't know what you're talking about here. There is no `dataclasses` requirement in `cycler`.
